name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-18.04, ubuntu-latest]
          python-version: ['3.6']
          #python-version: ['3.6', '3.7', '3.8','3.9']
      steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
        #- run: which python
        #- name: Run installation.
        #run: |
        # bash -e install.sh
        #- name: Test module imports
        #run: |
        # python <<< "import alpenglow"
        # python <<< "import twittercrawler" 
        # python <<< "import online_node2vec" 
